server:
  port: 8081
  servlet:
    context-path: /api
spring:
  application:
    name: party-builder-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/party_builder
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: validate