camel:
  springboot:
    main-run-controller: true
  component:
    rabbitmq:
      hostname: ${queue_host}
      port-number: ${queue_port:5672}
      username: ${queue_username}
      password: ${queue_password}
party-builder:
  api:
    url: http://localhost:8081/members/party